### ISSUE TITLE
results trained on COCO-stuff

### ISSUE THREAD

**Issue by wangkaihong** [bytedance/fc-clip#1]
Hi,

Thanks for releasing the incredible work! I wonder have you trained your method on COCO-stuff? It seems like that contains more information and should provide better semantic segmentation performance. If so, would you release the code as well?

**Comment by chaitanyakrishna1248** [comment]
Hi,
Is there an option to provide text as input to the model? Has it been included in any of the demo files as I want to use my text  prompt to segment an object and obtain its mask?
