### ISSUE TITLE
Detail about 'background' class

### ISSUE THREAD

**Issue by develop-productivity** [bytedance/fc-clip#11]
Hi, thanks for your great work. 

I have a question about the classifier in this paper, I want to know whether you used the 'background' class in the training. In vanllia maskformer, the author used the background class.  If you used a background class, is it learnable or fixed?

> Note, that the classifier predicts an additional "no object" category (∅) in case the embedding does not correspond to any region

**Comment by cornettoyu** [comment]
Hi,

We use a learnable "void" embedding as defined [here](https://github.com/bytedance/fc-clip/blob/main/fcclip/fcclip.py#L134).

Best,

**Comment by develop-productivity** [comment]
> Hi,
> 
> We use a learnable "void" embedding as defined [here](https://github.com/bytedance/fc-clip/blob/main/fcclip/fcclip.py#L134).
> 
> Best,

OK, I see. Thanks.
