### ISSUE TITLE
fc-clip模型的计算量和可训练参数量的评估代码

### ISSUE THREAD

**Issue by APeiZou** [bytedance/fc-clip#15]
@cornettoyu   你好， fc-clip模型的计算量和可训练参数量的评估代码有吗

**Comment by APeiZou** [comment]
@bytedance-oss-robot

**Comment by cornettoyu** [comment]
Hi,

We just updated the codes for computing parameters [here](https://github.com/bytedance/fc-clip/blob/main/train_net.py#L309) for your reference. For FLOPs, you may refer to [this file](https://github.com/facebookresearch/Mask2Former/blob/main/tools/analyze_model.py)

Best,

**Comment by APeiZou** [comment]
Thanks for you

**Comment by APeiZou** [comment]
![image](https://github.com/bytedance/fc-clip/assets/49524647/ea50b29a-5842-45fe-9171-ca50226eb8b0)
用新提供的计算代码计算的convnet_large为backbone的计算量如上
