### ISSUE TITLE
Demo result looks bad compared to hugging face.

### ISSUE THREAD

**Issue by qiwen-1123** [bytedance/fc-clip#16]
Hi, thanks for your great work. I tried to run the demo with the "FC-CLIP (ResNet50x64)" model and got some bad results, 
![nuscenes](https://github.com/bytedance/fc-clip/assets/141814250/cc514ef1-3ca0-4953-a4d6-c6ecd4339717)
But I also tried the hugging face, I got the certainly good results
![Screenshot from 2023-12-02 11-11-36](https://github.com/bytedance/fc-clip/assets/141814250/8c6767b3-e3d5-474a-b393-18f657c9644d)
Could give me some hints, what could be wrong?
Thanks in advance!

**Comment by cornettoyu** [comment]
Hi, we use ConvNeXt-L variant for huggingface demo, which should give different results to ResNet ones. But still, I also feel it looks weird in the RN results you obtained. Could you please provide the following information for debugging purposes?

1. Could you run local demo with ConvNeXt-L FC-CLIP to see if it gives the same results of huggingface demo?
2. Could you provide the command you used to obtain demo results?
3. I have never checked visualization from RN backbones, and we do observe that they exhibit some different properties, e.g., we need to [ensemble over valid masks](https://github.com/bytedance/fc-clip/blob/main/configs/coco/panoptic-segmentation/fcclip/fcclip_convnext_large_eval_ade20k_r50.yaml#L7) to have a reasonable PQ. Thus, it would also be helpful if you can provide visualization for semantic segmentation besides panoptic ones?

Best,

**Comment by qiwen-1123** [comment]
Thanks a lot, after switching into ConvNeXt-L FC-CLIP it works well.
