### ISSUE TITLE
huggingface_hub.utils._errors.LocalEntryNotFoundError:

### ISSUE THREAD

**Issue by Syloveslife** [bytedance/fc-clip#17]
Hi, I encountered this error when I tried to reproduce it, and I haven't found a way to solve this problem on the Internet. Can you provide me with some solutions? :）

As follows, 

huggingface_hub.utils._errors.LocalEntryNotFoundError: Connection error, and we cannot find the requested files in the disk cache. Please try again or make sure your Internet connection is on.

![1702008353277](https://github.com/bytedance/fc-clip/assets/35019207/1fb41c17-cd0a-40f3-9437-26e6052f5a0d)

**Comment by cornettoyu** [comment]
Hi,

it looks like you do not have Internet connection to huggingface. Please check if you can successfully download and load the pre-trained CLIP weights as in [this line](https://github.com/bytedance/fc-clip/blob/main/fcclip/modeling/backbone/clip.py#L34)

Best,

**Comment by Syloveslife** [comment]
Hi, 

appreciate so much for your quick reply,

pre-trained CLIP weights (convnext_large_d_320, laion2b_s29b_b131k_ft_soup) can not successfully download from that link, but another version (ViT-B/16, openai) can be downloaded normally.

**Comment by Syloveslife** [comment]
> Hi,
> 
> it looks like you do not have Internet connection to huggingface. Please check if you can successfully download and load the pre-trained CLIP weights as in [this line](https://github.com/bytedance/fc-clip/blob/main/fcclip/modeling/backbone/clip.py#L34)
> 
> Best,

Hi,

appreciate so much for your quick reply,

pre-trained CLIP weights (convnext_large_d_320, laion2b_s29b_b131k_ft_soup) can not successfully download from that link, but another version (ViT-B/16, openai) can be downloaded normally.

**Comment by cornettoyu** [comment]
> > Hi,
> > it looks like you do not have Internet connection to huggingface. Please check if you can successfully download and load the pre-trained CLIP weights as in [this line](https://github.com/bytedance/fc-clip/blob/main/fcclip/modeling/backbone/clip.py#L34)
> > Best,
> 
> Hi,
> 
> appreciate so much for your quick reply,
> 
> pre-trained CLIP weights (convnext_large_d_320, laion2b_s29b_b131k_ft_soup) can not successfully download from that link, but another version (ViT-B/16, openai) can be downloaded normally.

Hi,

I just tried that it still work in my end. The difference could be that ViT-B/16 OpenAI weight is hosted by OpenAI, while the ConvNeXt weight is hosted by huggingface. In this case, I would assume you may need some proxy to download the weight, or you could download the [weight ](https://huggingface.co/laion/CLIP-convnext_large_d_320.laion2B-s29B-b131K-ft-soup/tree/main) manually and change the pretrained weight path to your local files.

Best,

**Comment by Syloveslife** [comment]
> > > Hi,
> > > it looks like you do not have Internet connection to huggingface. Please check if you can successfully download and load the pre-trained CLIP weights as in [this line](https://github.com/bytedance/fc-clip/blob/main/fcclip/modeling/backbone/clip.py#L34)
> > > Best,
> > 
> > 
> > Hi,
> > appreciate so much for your quick reply,
> > pre-trained CLIP weights (convnext_large_d_320, laion2b_s29b_b131k_ft_soup) can not successfully download from that link, but another version (ViT-B/16, openai) can be downloaded normally.
> 
> Hi,
> 
> I just tried that it still work in my end. The difference could be that ViT-B/16 OpenAI weight is hosted by OpenAI, while the ConvNeXt weight is hosted by huggingface. In this case, I would assume you may need some proxy to download the weight, or you could download the [weight ](https://huggingface.co/laion/CLIP-convnext_large_d_320.laion2B-s29B-b131K-ft-soup/tree/main) manually and change the pretrained weight path to your local files.
> 
> Best,

The problem has been solved. Thanks a lot for your help. :)
