### ISSUE TITLE
Combining In- and Out-of-Vocabulary Classifiers

### ISSUE THREAD

**Issue by slonetime** [bytedance/fc-clip#19]
1

**Comment by slonetime** [comment]
Hi, authors, thanks for your great work!
I have a question, that is, in the paper, you mentioned "Following prior works [30, 28, 44, 84], we employ geometric ensemble to fuse the classification scores between in-vocabulary and out-of vocabulary classifiers ". I notice that [28] is OpenSeg and I have read the OpenSeg paper. But I can't find where they use this ensembling strategy. And it seems that they haven't released the code.

**Comment by cornettoyu** [comment]
> Hi, authors, thanks for your great work! I have a question, that is, in the paper, you mentioned "Following prior works [30, 28, 44, 84], we employ geometric ensemble to fuse the classification scores between in-vocabulary and out-of vocabulary classifiers ". I notice that [28] is OpenSeg and I have read the OpenSeg paper. But I can't find where they use this ensembling strategy. And it seems that they haven't released the code.

Thanks for the note! Yes you are right that OpenSeg does not use geometric ensemble according to their paper, sorry for the confusion in the reference mistake, we will revise that part correspondingly.

**Comment by slonetime** [comment]
OK, thanks for your timely reply.
