### ISSUE TITLE
Text prompt for FC-CLIP

### ISSUE THREAD

**Issue by chaitanyakrishna1248** [bytedance/fc-clip#2]
Hi,
Is there an option to provide text as input to the model? Has it been included in any of the demo files as I want to use my text prompt to segment an object and obtain its mask?

**Comment by cornettoyu** [comment]
Hi,

You can try it in the provided [huggingface demo](https://huggingface.co/spaces/fun-research/FC-CLIP), where you can input your own text for class names. You can also edit it [here in the code](https://github.com/bytedance/fc-clip/blob/main/demo/predictor.py#L124) to insert user classes and run the demo.py (see [here](https://github.com/bytedance/fc-clip/blob/main/GETTING_STARTED.md) for how to run demo.py)

Best,

**Comment by chaitanyakrishna1248** [comment]
Alright, thank you so much!
