### ISSUE TITLE
About FPS comparison

### ISSUE THREAD

**Issue by nhw649** [bytedance/fc-clip#23]
Hello~
ODISE mentions that "It performs inference for an image (10242) at 1.26 FPS on an NVIDIA V100 GPU and uses 11.9 GB". This does not match the data in table 4. Could you please provide more detailed settings? For example, image size and so on.

**Comment by cornettoyu** [comment]
Once you run the testing, you will have a testing log file (for both ODISE or FC-CLIP), like [the one ](https://github.com/bytedance/fc-clip/blob/main/logs/testing/ade20k.log#L195)we provided, which provides the total time for inferring on the whole test set. We report FPS based on number of images / total time to provide a practical estimate on FPS, following Mask2Former

**Comment by nhw649** [comment]
ok，thanks.
