### ISSUE TITLE
Results with ResNets

### ISSUE THREAD

**Issue by helen1c** [bytedance/fc-clip#8]
In code you have resnet configurations, but there are no resnet results in the paper. Were those results bad? Could you share your insights?

**Comment by cornettoyu** [comment]
Hi, we have provided ResNet results/weight in the model zoo, please take a look. We just have not updated the number in the paper yet but will do :)

**Comment by helen1c** [comment]
Hi @cornettoyu. Sorry. While reading the paper, I didn't see those results, so I thought they aren't published. Thank you for results, and awesome work! :)
