### ISSUE TITLE
Question about mask-pooling for out-vocab branch

### ISSUE THREAD

**Issue by ZhihaoZhu** [bytedance/fc-clip#9]
Hi, 

Thanks for sharing the code for the great work. 
I just have one question for the out-vocab branch inference: how do you perform mask-pooling on the low-resolution Clip feature? Since your predicted mask is of higher-resolution compared to the lower-resolution clip feature extracted from backbone, do you down-sample the predicted mask and then do mask-pooling?

Thanks

**Comment by cornettoyu** [comment]
Yes, the mask will be downsampled to match the res of clip feature

**Comment by ZhihaoZhu** [comment]
Ah I see, thank you for the reply. 
Another question is:  is it a problem that the visual features used for training and inference are different: for the training (in-vocab branch), we are doing mask-pooling on the pixel decoder feature, while for the inference, we are doing mask-pooling on pixel decoder feature space (in-vocab)+ clip feature space(out-vocab).  Do you think this discrepancy would cause issues?

**Comment by cornettoyu** [comment]
Thanks for your question. I think it works fine considering many model ensemble methods do this in a similar way (i.e., each model is not aware of other models to be ensembled). But I do agree that it may lead to a better performance if they are aware of the existence of other models/predictions.

**Comment by ZhihaoZhu** [comment]
That makes sense, thanks!
